services:
  magi:
    build:
      context: ./config/magi  # Builds from magi folder
      dockerfile: ../Dockerfile  # Uses shared root Dockerfile
    container_name: magi-bot
    restart: unless-stopped
    env_file:
      - magi/.env  # Loads magi-specific config
    volumes:
      - ./logs/magi:/app/logs  # Isolated logs for magi

  corrupt-magi:
    build:
      context: ./config/corrupt-magi
      dockerfile: ../Dockerfile
    container_name: corrupt-magi-bot
    restart: unless-stopped
    env_file:
      - corrupt-magi/.env
    volumes:
      - ./logs/corrupt-magi:/app/logs  # Isolated logs for corrupt-magi

  carlin:
    build:
      context: ./config/carlin
      dockerfile: ../Dockerfile
    container_name: carlin-bot
    restart: unless-stopped
    env_file:
      - carlin/.env
    volumes:
      - ./logs/carlin:/app/logs  # Isolated logs for carlin
